# Generated by Django 6.0.3 on 2026-04-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='log_source_path',
            new_name='sshKey',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deployed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_deployment_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='server_config',
        ),
        migrations.RemoveField(
            model_name='project',
            name='special_features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
