# Generated by Django 6.0.3 on 2026-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0002_rename_log_source_path_project_sshkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rootDir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sshKey',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
