# Generated by Django 6.0.3 on 2026-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0003_project_rootdir_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rootDir',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='sshKey',
            field=models.CharField(max_length=500),
        ),
    ]
