# Generated by Django 6.0.3 on 2026-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0004_alter_project_rootdir_alter_project_sshkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='userDeployCommands',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
