// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  user_id: __t.u64(),
  django_project_id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  ssh_key: __t.string(),
  server_ip: __t.string(),
  root_directory: __t.string(),
  deploy_commands: __t.string(),
});
