// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentEvent = __t.object("AgentEvent", {
  id: __t.u64(),
  incidentId: __t.string(),
  eventType: __t.string(),
  payload: __t.string(),
  timestamp: __t.timestamp(),
});
export type AgentEvent = __Infer<typeof AgentEvent>;

export const AiDecision = __t.object("AiDecision", {
  id: __t.u64(),
  incidentId: __t.u64(),
  analysis: __t.string(),
  command: __t.string(),
  confidence: __t.f64(),
});
export type AiDecision = __Infer<typeof AiDecision>;

export const Execution = __t.object("Execution", {
  id: __t.u64(),
  incidentId: __t.u64(),
  status: __t.string(),
  output: __t.string(),
});
export type Execution = __Infer<typeof Execution>;

export const Incident = __t.object("Incident", {
  id: __t.u64(),
  service: __t.string(),
  status: __t.string(),
  logs: __t.string(),
  timestamp: __t.timestamp(),
});
export type Incident = __Infer<typeof Incident>;

export const SafetyCheck = __t.object("SafetyCheck", {
  id: __t.u64(),
  incidentId: __t.u64(),
  allowed: __t.bool(),
  reason: __t.string(),
});
export type SafetyCheck = __Infer<typeof SafetyCheck>;

