# Generated by Django 6.0.3 on 2026-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
