// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAiDecisionReducer from "../add_ai_decision_reducer";
import AddSafetyCheckReducer from "../add_safety_check_reducer";
import CreateIncidentReducer from "../create_incident_reducer";
import EmitEventReducer from "../emit_event_reducer";
import ResolveIncidentReducer from "../resolve_incident_reducer";
import StartExecutionReducer from "../start_execution_reducer";

export type AddAiDecisionParams = __Infer<typeof AddAiDecisionReducer>;
export type AddSafetyCheckParams = __Infer<typeof AddSafetyCheckReducer>;
export type CreateIncidentParams = __Infer<typeof CreateIncidentReducer>;
export type EmitEventParams = __Infer<typeof EmitEventReducer>;
export type ResolveIncidentParams = __Infer<typeof ResolveIncidentReducer>;
export type StartExecutionParams = __Infer<typeof StartExecutionReducer>;

